### ISSUE TITLE
"Get help with this page" does not render locally

### ISSUE THREAD

**Issue by callumcodes** [hmrc/hmrc-frontend-scaffold.g8#25]
# "Get help with this page" does not render locally

The "Get help with this page" link does not render the view locally even with the service running.
This is because the port contact-frontend runs on is blocked by the security policy.

![gethelp](https://user-images.githubusercontent.com/9841956/34942693-841328bc-f9f0-11e7-8fae-557974fb74b3.gif)

## Proposed solution

Add the contact-frontend port to the security policy.

## How to recreate

Click "Get help with this page"

**Comment by TheNickWilson** [comment]
Thanks @callumcodes :+1:
