### ISSUE TITLE
Language toggle causes failing tests

### ISSUE THREAD

**Issue by garethgooch** [hmrc/hmrc-frontend-scaffold.g8#39]
## Language toggle causes failing tests

If you update the application.conf file to have "welsh-translation: false" this will then cause each view to fail tests for the ViewBehaviours  "display language toggles" tests.

## Proposed solution

Add a logic into the test to check if the language toggle is required, if true then run test else ignore the test as this is now redundant.

## How to recreate

Open the applicaion.conf file in a project with views and switch "welsh-translation: true" to "false", run sbt test.

**Comment by TheNickWilson** [comment]
@garethgooch this is desired behaviour.  If you want to change the behaviour of your application (e.g. by turning the language toggles off), we would expect that you update the specs to reflect the behaviour you expect.
